server:
  port: 9000

spring:
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: foo-1
      auto-offset-reset: earliest
